package io.code.morning.infrastructure

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "blog")
data class BlogEntity(
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    var category: String? = null,

    @DynamoDBAttribute
    var title: String? = null,

    @DynamoDBAttribute
    var detail: String? = null
)
