package io.code.morning.infrastructure

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "Blog")
data class BlogEntity(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    val id: String? = null,

    @DynamoDBAttribute
    val category: String? = null,

    @DynamoDBAttribute
    val title: String? = null,

    @DynamoDBAttribute
    val detail: String? = null
)
