spring:
  profiles:
    active: local

server:
  port: 9081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

amazon:
  dynamodb:
    endpoint: http://localhost:8000
  credential:
    profile: default
