/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.code.morning

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest


@SpringBootTest
class BlogServiceApplicationTest {

  @Test
  fun contextLoads() {
  }
}
