/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.code.morning

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class BlogServiceApplication

fun main(args: Array<String>) {
  runApplication<BlogServiceApplication>(*args)
}
